install.packages(
  "remotes",
  "caTools",
  #"devtools",
  "dplyr",
  "dygraphs",
  "eflows",
  "eflows.viz",
  "knitr",
  "R6",
  "readr",
  #"renv",
  "rmarkdown",
  "shiny",
  "shinyAce",
  "shinydashboard",
  "shinyjs",
  "shinyWidgets",
  "tidyr"
)

remotes::install_github("cvmartin/eflows")
remotes::install_github("cvmartin/eflows.viz")